### ISSUE TITLE
No module named 'src' 

### ISSUE THREAD

**Issue by fhcbvdjknl** [sosppxo/MDIN#10]
According to your code, the following error occurs during runtime. How can I resolve this issue?
![image](https://github.com/user-attachments/assets/91b06687-9dd5-4b24-a6d9-3be773d3e43b)

**Comment by sosppxo** [comment]
We have added it to the repo, please update to fix it. Thanks for your issue!

**Comment by fhcbvdjknl** [comment]
No such file or directory: 'mapping_full2rio27.json'.Thanks for your reply!
![image](https://github.com/user-attachments/assets/93f54905-ff11-49b3-a6f1-b47e34e1902f)

**Comment by sosppxo** [comment]
We have just updated it. Thanks for your attention~
