### ISSUE TITLE
i cannot find setup.py

### ISSUE THREAD

**Issue by m28yhtd** [sosppxo/MDIN#2]
README.md / Installation

> Setup, Install mdin and pointgroup_ops.
> 
> sudo apt-get install libsparsehash-dev
> python setup.py develop

where can I find the setup.py file?

**Comment by m28yhtd** [comment]
![image](https://github.com/user-attachments/assets/2d3194af-648a-452e-9e67-72681c9bf067)

Thank you for accepting my suggestion.
However, there is still an error in execution, so I would like to suggest it again.
What should I do in this case?

**Comment by m28yhtd** [comment]
![image](https://github.com/user-attachments/assets/276755a7-c1b7-4cc9-9df1-0cefbfea5133)
An error occurred while trying to run the code, so I checked and found the following code. 
After that, I downloaded roberta-base by referring to EDA.

![image](https://github.com/user-attachments/assets/c13e2e9f-685b-4a02-a0b8-73f4bbf13ed4)
However, the error occurred after downloading roberta-base.

**Comment by sosppxo** [comment]
> ![image](https://private-user-images.githubusercontent.com/117574641/359303951-2d3194af-648a-452e-9e67-72681c9bf067.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzU2MzMsIm5iZiI6MTcyNDEzNTMzMywicGF0aCI6Ii8xMTc1NzQ2NDEvMzU5MzAzOTUxLTJkMzE5NGFmLTY0OGEtNDUyZS05ZTY3LTcyNjgxYzliZjA2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwNjI4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGQ0ZWE3NjRhNGUxYzhiNjcwZTFhZDhmOGFmODFhZDg2Y2QwOWJkMjEyZjkzZDgwOWY1Njc5NWExYjg0ZGMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mpzvA6UhyKEH3VUQUAC-MuYkfs0QoCcZco5FC1metNY)
> 
> Thank you for accepting my suggestion. However, there is still an error in execution, so I would like to suggest it again. What should I do in this case?
> 
> ![image](https://private-user-images.githubusercontent.com/117574641/359308240-8ccabf52-80bf-4767-97f1-1abf89d1043a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzU2MzMsIm5iZiI6MTcyNDEzNTMzMywicGF0aCI6Ii8xMTc1NzQ2NDEvMzU5MzA4MjQwLThjY2FiZjUyLTgwYmYtNDc2Ny05N2YxLTFhYmY4OWQxMDQzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwNjI4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmExMmUyZDJjOTNjNzdmMGJmYjhmZDhmMjk1Zjc1ZWI2NWY2ZWJlZWEzODhjYzA1ZjczMjhjODVmNTgzZWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tdC4aHIi9-yzHax6F8072sAY2ddI3muxFHN4HE93n1Y) and where can I download 'pointnet2'?

Hi, 'pointnet2' can be found in the EDA repo, you can copy the folder and install it. We will update soon.
