### ISSUE TITLE
How can I visualize the results?

### ISSUE THREAD

**Issue by m28yhtd** [sosppxo/MDIN#3]
![image](https://github.com/user-attachments/assets/826452d2-51e3-47b1-81cc-d8f014bac02c)

From Inference I got the json files for the results.

How can I get a visualization of the results?

**Comment by m28yhtd** [comment]
![image](https://github.com/user-attachments/assets/ac28b9d4-0404-4bb1-9515-52a408437856)
When I ran inference for the 3D-GRES task, the following error occurred.

![image](https://github.com/user-attachments/assets/ee0b9a7a-e822-4f32-8ec5-d2f4d95e2ba6)
To resolve the error, I commented out the part as described in the description, but an error occurred related to that part.

![image](https://github.com/user-attachments/assets/8dbaf5e0-a481-47e8-98d4-d608295bcee2)
So I added the code and tried to output the cause.

![image](https://github.com/user-attachments/assets/0d85b9b7-a338-4fc4-a002-f8232110e4f1)
There is a mismatch between token_text and token_list[id].

**Comment by emptyttt** [comment]
Could you please tell me how you obtained the visualization results?
